// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NearFind.API.Data;

#nullable disable

namespace NearFind.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260915141416_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NearFind.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Salons, spas and personal wellness services",
                            Name = "Beauty"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Clinics, doctors and healthcare services",
                            Name = "Healthcare"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Gyms, yoga studios and fitness centers",
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Boutiques, clothing and fashion services",
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Restaurants, cafes and food services",
                            Name = "Food"
                        });
                });

            modelBuilder.Entity("NearFind.API.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rating")
                        .HasPrecision(2, 1)
                        .HasColumnType("decimal(2,1)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Andheri West",
                            CategoryId = 1,
                            City = "Mumbai",
                            Description = "Professional beauty and wellness services with experienced stylists.",
                            ImageUrl = "",
                            Latitude = 19.136399999999998,
                            Longitude = 72.829599999999999,
                            Name = "Glow Beauty Studio",
                            Phone = "9876543210",
                            Rating = 4.8m,
                            ReviewCount = 124
                        },
                        new
                        {
                            Id = 2,
                            Address = "Thane West",
                            CategoryId = 1,
                            City = "Thane",
                            Description = "Beauty studio offering styling and personal care services.",
                            ImageUrl = "",
                            Latitude = 19.218299999999999,
                            Longitude = 72.978099999999998,
                            Name = "Style Studio",
                            Phone = "9876543211",
                            Rating = 4.5m,
                            ReviewCount = 87
                        },
                        new
                        {
                            Id = 3,
                            Address = "Powai",
                            CategoryId = 2,
                            City = "Mumbai",
                            Description = "A trusted clinic providing quality healthcare and diagnostic services.",
                            ImageUrl = "",
                            Latitude = 19.117599999999999,
                            Longitude = 72.906000000000006,
                            Name = "MediCare Clinic",
                            Phone = "9876543212",
                            Rating = 4.9m,
                            ReviewCount = 156
                        },
                        new
                        {
                            Id = 4,
                            Address = "Bandra West",
                            CategoryId = 3,
                            City = "Mumbai",
                            Description = "Modern fitness center offering training, yoga and wellness programs.",
                            ImageUrl = "",
                            Latitude = 19.060700000000001,
                            Longitude = 72.836200000000005,
                            Name = "FitZone Fitness",
                            Phone = "9876543213",
                            Rating = 4.6m,
                            ReviewCount = 98
                        },
                        new
                        {
                            Id = 5,
                            Address = "Lower Parel",
                            CategoryId = 4,
                            City = "Mumbai",
                            Description = "Contemporary fashion and styling for everyday and special occasions.",
                            ImageUrl = "",
                            Latitude = 18.998799999999999,
                            Longitude = 72.825800000000001,
                            Name = "Urban Threads",
                            Phone = "9876543214",
                            Rating = 4.4m,
                            ReviewCount = 76
                        },
                        new
                        {
                            Id = 6,
                            Address = "Dadar West",
                            CategoryId = 5,
                            City = "Mumbai",
                            Description = "A local restaurant serving authentic Indian dishes and regional flavors.",
                            ImageUrl = "",
                            Latitude = 19.017800000000001,
                            Longitude = 72.847800000000007,
                            Name = "Mumbai Spice",
                            Phone = "9876543215",
                            Rating = 4.7m,
                            ReviewCount = 212
                        });
                });

            modelBuilder.Entity("NearFind.API.Models.Vendor", b =>
                {
                    b.HasOne("NearFind.API.Models.Category", "Category")
                        .WithMany("Vendors")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NearFind.API.Models.Category", b =>
                {
                    b.Navigation("Vendors");
                });
#pragma warning restore 612, 618
        }
    }
}
